name: 2022_crawford_1
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - alchemlyb=1.0.0
  - astunparse=1.6.3
  - attrs=22.1.0
  - blosc=1.21.1
  - boltons=21.0.0
  - boost=1.78.0
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.0
  - colorama=0.4.6
  - contourpy=1.0.6
  - cryptography=38.0.4
  - cycler=0.11.0
  - deprecation=2.1.0
  - ele=0.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - filelock=3.8.0
  - flask=2.2.2
  - flask-assets=2.0
  - flask-turbolinks=0.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - forcefield-utilities=0.2.1
  - foyer=0.11.3
  - freetype=2.12.1
  - freud=2.12.0
  - garnett=0.7.1
  - gettext=0.21.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gmso=0.9.1
  - greenlet=2.0.1
  - gsd=2.6.1
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - importlib-metadata=5.1.0
  - importlib_resources=5.10.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsmin=3.0.1
  - jsonschema=4.17.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lark-parser=0.12.0
  - lcms2=2.14
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran5=11.3.0
  - libglib=2.74.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.21.9
  - libsass=0.21.0
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=15.0.5
  - lxml=4.9.1
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - mbuild=0.15.1
  - mdtraj=1.9.7
  - mosdef-gomc=1.0.0
  - mpc=1.2.1
  - mpfr=4.1.0
  - mpmath=1.2.1
  - munkres=1.1.4
  - natsort=8.2.0
  - ncurses=6.3
  - networkx=2.8.8
  - numexpr=2.8.3
  - numpy=1.23.5
  - openjpeg=2.5.0
  - openmm=7.7.0
  - openssl=3.0.8
  - packaging=21.3
  - packmol=20.010
  - pandas=1.5.2
  - parmed=3.4.3
  - pcre2=10.40
  - pillow=9.2.0
  - pip=22.3.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - protobuf=4.21.9
  - pthread-stubs=0.4
  - pycairo=1.23.0
  - pycifrw=4.4.5
  - pycparser=2.21
  - pydantic=1.10.2
  - pymbar=3.1.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyrsistent=0.19.2
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.9.15
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.6
  - pyyaml=6.0
  - rdkit=2022.09.1
  - readline=8.1.2
  - reportlab=3.5.68
  - requests=2.28.1
  - rowan=1.3.0.post1
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - setuptools=65.5.1
  - signac=1.7.0
  - signac-dashboard=0.3.1
  - signac-flow=0.22.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlalchemy=1.4.44
  - sympy=1.10.1
  - tbb=2021.7.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tornado=6.2
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022f
  - unicodedata2=15.0.0
  - unyt=2.9.2
  - urllib3=1.26.13
  - watchdog=2.1.9
  - webassets=2.0
  - werkzeug=2.2.2
  - wheel=0.38.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2

